CHS Patchouli Guide Translation
elseytd/TheAurorian pull request #17
Opened 2020-08-26 05:42 UTC by WuzgXY-GitHub

2020-08-28 02:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/blocks/aurorianfurnace.json
> +            "text": "与原版的熔炉相同，但你可以在上方放置孔道来加快熔炼速度！$(br2)速度和孔道最大数量可以在配置文件中被修改。孔道之间也可以被摆放上方块以实现无缝覆盖。"
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
            "text": "与原版的熔炉相同，但你可以在上方放置孔道来加快熔炼速度！$(br2)速度和孔道最大数量可以在配置文件中被修改。"
```
删掉的这一句我不会，需要帮助。

2020-08-28 02:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/7moontemplemobs.json
> +            "text": "$(#8800ff)皎月女王$()是$(#008cff)月宫$()的 BOSS。她会使用自己的护盾将你围起来并 perform shield charges 以将你击飞至空中！"
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
            "text": "$(#8800ff)皎月女王$()是$(#008cff)月宫$()的 BOSS。她会使用自己的护盾将你围起来并充能以将你击飞至空中！"
```
删掉的这一句我不会，需要帮助。

2020-08-28 02:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/7moontemplemobs.json
> +            "text": "$(#008cff)晶魂$()会在空中向玩家发射火焰。"
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
            "text": "$(#008cff)晶魂$()。"
```
删掉的这一句需要实测。

2020-08-28 02:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/6moontemple.json
> +            "text": "$(#8800ff)蛛母$()会掉落能通往下一座地牢的$(#008cff)暗黑护符$()。$(br2)$(#008cff)月宫$()的内部有两座塔。塔顶会有$(#008cff)月宫内室钥匙碎片$()。"
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
            "text": "$(br2)$(#008cff)月宫$()的内部有两座塔。塔顶会有$(#008cff)月宫内室钥匙碎片$()。"
```
删掉的这一句需要实测。

2020-08-28 02:35 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/7moontemplemobs.json
> +            "text": "$(#8800ff)皎月女王$()是$(#008cff)月宫$()的 BOSS。她会使用自己的护盾将你围起来并 perform shield charges 以将你击飞至空中！"
我感觉意思是对着敌人充能。

2020-08-28 03:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/aurorianslimeboots.json
> +            "text": "$(#008cff)极光粘液靴子$()能让你在下蹲时跳得更高！它同样也会减少你的摔落伤害。默认情况下高跳之间有 5 秒的冷却。"
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
            "text": "$(#008cff)极光粘液靴子$()！它同样也会减少你的摔落伤害。默认情况下高跳之间有 5 秒的冷却。"
```
删掉的这句话需要实测。

2020-08-28 03:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/absorptionorb.json
> +            "text": "$(#008cff)修损宝珠$()可以在在副手时恢复你主手物品的耐久度！"
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
            "text": "$(#008cff)修损宝珠$()可以恢复你主手物品的耐久度！"
```
删掉的这句话需要实测。

2020-08-28 03:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/aurorianitesword.json
> +            "text": "$(#008cff)极光剑$()在攻击时会让周围的所有人一同失重！默认情况下会有 30 秒的冷却（可在配置文件中调整）。$(br2)如果有盾牌或其它物品在你的副手上时你需要潜行以激活它。"
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
            "text": "$(#008cff)极光剑$()在攻击时会让周围的所有人一同失重！默认情况下会有 30 秒的冷却（可在配置文件中调整）。"
```
删掉的这句话需要实测。

2020-08-28 03:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/umbrasword.json
> +            "text": "$(#008cff)本影剑$()会给予玩家 6 秒的伤害吸收、抗性提升、虚弱以及缓慢效果。当你处于胶着状态且十分需要生命值的恢复时相当有用！$(br2)如果有盾牌或其它物品在你的副手上时你需要潜行以激活它。"
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
            "text": "$(#008cff)本影剑$()会给予玩家 6 秒的伤害吸收、抗性提升、虚弱以及缓慢效果。当你处于胶着状态且十分需要生命值的恢复时相当有用！$(br2)如果有盾牌或其它物品在你的副手上时你需要潜行以激活它。"
```
删掉的这句话需要实测。

2020-08-28 03:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/umbrapickaxe.json
> +            "text": "$(#008cff)本影镐$()能让你选择一种方块并获得挖掘它时的速度增益，但选择这一过程会消耗大量耐久度。潜行单击一个方块会移除当前选中的方块。"
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
            "text": "$(#008cff)本影镐$()能让你选择一种方块并获得挖掘它时的速度增益，但选择这一过程会消耗大量耐久度。"
```
删掉的这句话需要实测。

2020-08-28 03:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/lang/zh_cn.lang
> +item.theaurorian.moonshield.name=皎月之盾
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
item.theaurorian.moonshield.name=皎月之盾牌
```
失去了美感，所以没有采用。

2020-08-28 03:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/lang/zh_cn.lang
> +entity.theaurorian.crystallinesprite.name=月凝晶魂
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

这个词需要实测。

2020-08-28 03:00 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/7moontemplemobs.json
> +            "text": "$(#008cff)月凝晶魂$()会在空中向玩家发射火焰。"
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

同上，这个词需要实测。

2020-08-28 07:17 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/lang/zh_cn.lang
> +enchantment.theaurorian.lightningresistance=雷电抵御
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

需要更有美感的译名。

2020-08-28 15:35 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/agriculture/lavender.json
> +            "text": "$(#008cff)薰衣草$()是极光幽境中一种很常见的植物！你需要使用镰来采集薰衣草，如果想要种植它则需要将其转化为$(#008cff)薰衣草籽$()。"
```suggestion
            "text": "$(#008cff)薰衣草$()是极光幽境中一种很常见的植物！你需要使用镰来采集薰衣草，如果想要种植它，则需要将其制作为$(#008cff)薰衣草籽$()。"

```

2020-08-28 16:16 UTC, TUsama requested changes

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/agriculture/lavender.json
> +            "text": "$(#008cff)薰衣草$()是极光幽境中一种很常见的植物！你需要使用镰来采集薰衣草，如果想要种植它则需要将其转化为$(#008cff)薰衣草籽$()。"
```suggestion
            "text": "$(#008cff)薰衣草$()是极光幽境中一种很常见的植物！你需要使用镰来采集薰衣草，如果想要种植它，则需要将其制作为$(#008cff)薰衣草籽$()。"

```

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/agriculture/silkberry.json
> +            "text": "$(#008cff)桑葚酱$()自身并没有什么可圈可点的地方，但是包含它和$(#008cff)薰衣草面包$()的$(#008cff)桑葚酱三明治$()相当不错！"
```suggestion
            "text": "$(#008cff)桑葚酱$()自身并没有什么可圈可点的地方，但是将其与$(#008cff)薰衣草面包$()搭配，制作出的$(#008cff)桑葚酱三明治$()相当不错！"


```

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/agriculture/weepingwillowsap.json
> +            "text": "$(#008cff)垂柳树液$()可以从垂柳木上获取到。它们可以被用作燃料，也可以食用以将中毒效果变为缓慢效果。"
```suggestion
            "text": "$(#008cff)垂柳木树液$()可以从垂柳木上获取到。它们可以被用作燃料，也可以食用，食用后可将玩家的中毒效果变为缓慢效果。"


```

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/aurorianbasics/5lootscrapping.json
> +            "text": "$(#008cff)极光钢$()是极光幽境中最强大的材料，它可以被制成工具和盔甲。在$(#008cff)魔法物品$()部分中查看更多的信息。"
```suggestion
            "text": "$(#008cff)极光钢$()是极光幽境中最强大的材料，它可以被制成工具和盔甲。你可以在$(#008cff)魔法物品$()部分中查看更多的信息。"

```
时刻注意动词原形打头的句子，这种句子作为祈使句会省略掉人称，所以翻译时一定要补足，而且根据句子的需要，可以将祈使语气翻译或者较弱地翻译出来

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/aurorianitesword.json
> +            "text": "$(#008cff)极光剑$()在攻击时会让周围的所有人一同失重！默认情况下会有 30 秒的冷却（可在配置文件中调整）。$(br2)如果有盾牌或其它物品在你的副手上时你需要潜行以激活它。"
没有问题，注意加个逗号，让句子变得通顺一点，还有不知道为什么如果....和....时 以外的让我感到古怪。

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/strangemeat.json
> +            "text": "$(#008cff)怪异的肉$()本身相当充实，并且需要很长的一段时间来食用。但是在你吃完后，你会随机获得一种原版的正面效果！"
```suggestion
            "text": "$(#008cff)怪异的肉$()相当填肚子，并且需要很长的一段时间来食用。但是在你吃完后，你会随机获得一种原版的正面效果！"

```

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/umbrapickaxe.json
> +            "text": "$(#008cff)本影镐$()能让你选择一种方块并获得挖掘它时的速度增益，但选择这一过程会消耗大量耐久度。潜行单击一个方块会移除当前选中的方块。"
无问题。

```suggestion
            "text": "$(#008cff)本影镐$()能让你选择一种方块，并获得挖掘这种方块时获得速度增益，但选择这一过程会消耗大量耐久度。潜行单击一个方块会移除当前选中的方块。"


```

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/4darkstonedungeon.json
> +            "text": "$(#008cff)暗石地牢$()的入口位于地表，它将会带领你穿过重重叠叠如迷宫般的、被蜘蛛占领的、地牢。你必须找到$(#8800ff)蛛母$()并击杀它！"
```suggestion
            "text": "$(#008cff)暗石地牢$()的入口位于地表，大门之下将会是重重叠叠如迷宫般的、被蜘蛛占领的地牢。你必须找到$(#8800ff)蛛母$()并击杀它！"


```

2020-08-28 16:16 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/7moontemplemobs.json
> +            "text": "$(#8800ff)皎月女王$()是$(#008cff)月宫$()的 BOSS。她会使用自己的护盾将你围起来并 perform shield charges 以将你击飞至空中！"
就按着你的意思翻

2020-08-28 16:31 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/agriculture/weepingwillowsap.json
> +            "text": "$(#008cff)垂柳树液$()可以从垂柳木上获取到。它们可以被用作燃料，也可以食用以将中毒效果变为缓慢效果。"
食用后 会 将

2020-08-28 16:32 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/aurorianitesword.json
> +            "text": "$(#008cff)极光剑$()在攻击时会让周围的所有人一同失重！默认情况下会有 30 秒的冷却（可在配置文件中调整）。$(br2)如果有盾牌或其它物品在你的副手上时你需要潜行以激活它。"
不是你古怪，这是我的问题

2020-08-28 16:33 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/umbrapickaxe.json
> +            "text": "$(#008cff)本影镐$()能让你选择一种方块并获得挖掘它时的速度增益，但选择这一过程会消耗大量耐久度。潜行单击一个方块会移除当前选中的方块。"
冗余。

2020-08-28 16:33 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/7moontemplemobs.json
> +            "text": "$(#8800ff)皎月女王$()是$(#008cff)月宫$()的 BOSS。她会使用自己的护盾将你围起来并 perform shield charges 以将你击飞至空中！"
OK

2020-08-28 16:33 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/4darkstonedungeon.json
> +            "text": "$(#008cff)暗石地牢$()的入口位于地表，它将会带领你穿过重重叠叠如迷宫般的、被蜘蛛占领的、地牢。你必须找到$(#8800ff)蛛母$()并击杀它！"
一般。

2020-08-28 16:34 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/aurorianbasics/5lootscrapping.json
> +            "text": "$(#008cff)极光钢$()是极光幽境中最强大的材料，它可以被制成工具和盔甲。在$(#008cff)魔法物品$()部分中查看更多的信息。"
要改的多了，麻烦帮忙搜索一下，关键词应该就`部分`和`章节`

2020-08-29 02:20 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/aurorianslimeboots.json
> +            "text": "$(#008cff)极光粘液靴子$()能让你在下蹲时跳得更高！它同样也会减少你的摔落伤害。默认情况下高跳之间有 5 秒的冷却。"
实际上确实是这样

2020-08-29 02:25 UTC, TUsama commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/4darkstonedungeon.json
> +            "text": "$(#008cff)暗石地牢$()的入口位于地表，它将会带领你穿过重重叠叠如迷宫般的、被蜘蛛占领的、地牢。你必须找到$(#8800ff)蛛母$()并击杀它！"
最基础错误，lead down就是指在其下有着.....你直接翻译成“带领”，你跟我说这是一般？

2020-09-08 12:34 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/4darkstonedungeon.json
> +            "text": "$(#008cff)暗石地牢$()的入口位于地表，它将会带领你穿过重重叠叠如迷宫般的、被蜘蛛占领的、地牢。你必须找到$(#8800ff)蛛母$()并击杀它！"
我说一般不是说你指出我错误这件事一般，而是你改完了读着还不如我原先的通顺。你头疼与否与我的译本质量并没有关系，所以还请不要过分激动。改掉吧，改掉吧，改就对了。

2020-09-08 12:34 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/4darkstonedungeon.json
> +            "text": "$(#008cff)暗石地牢$()的入口位于地表，它将会带领你穿过重重叠叠如迷宫般的、被蜘蛛占领的、地牢。你必须找到$(#8800ff)蛛母$()并击杀它！"
建议在大门之下前面加个其字

2020-09-08 12:35 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/magicalitems/aurorianitesword.json
> +            "text": "$(#008cff)极光剑$()在攻击时会让周围的所有人一同失重！默认情况下会有 30 秒的冷却（可在配置文件中调整）。$(br2)如果有盾牌或其它物品在你的副手上时你需要潜行以激活它。"
不是你古怪，是我的问题，改。
这句话我以前回复过一遍，后来被吞了

2020-09-08 12:36 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/agriculture/silkberry.json
> +            "text": "$(#008cff)桑葚酱$()自身并没有什么可圈可点的地方，但是包含它和$(#008cff)薰衣草面包$()的$(#008cff)桑葚酱三明治$()相当不错！"
搭配后面加个后字

2020-09-08 12:37 UTC, WuzgXY-GitHub commented on TheAurorian/src/main/resources/assets/theaurorian/patchouli_books/the_aurorian_guide/zh_cn/entries/modprogression/4darkstonedungeon.json
> +            "text": "$(#008cff)暗石地牢$()的入口位于地表，它将会带领你穿过重重叠叠如迷宫般的、被蜘蛛占领的、地牢。你必须找到$(#8800ff)蛛母$()并击杀它！"
绝了，我当然看不出来，我看得出来还会认为自己是对的？

2020-09-08 13:14 UTC, TUsama approved these changes

2020-09-08 13:14 UTC, TUsama commented
It can be merged, everything is finished.

2020-10-03 00:12 UTC, merged